### PR TITLE
Fixed #11 Error making cors request while in offline scenario.

### LINKED ISSUE #11: Error making cors request while in offline scenario.
I just have a very basic index.html file (demo) and I'm running it locally and I'm getting a cors request. I think we should just do a try catch and return return Promise.reject(e); or Promise.reject(e.message). Thoughts?

image

### PR DESCRIPTION
**Pull request by niemyjski**
I've verified this fix locally :)

### CODE REVIEW

**Comment by eriwen** [comment]
Thanks for the pull request.

Couple things:
* While try/catch works, it is generally better to take advantage of Promise.catch(callback) because code just outside the try/catch block could throw Errors. There is an example of its use in the unit tests.
* This PR modifies the dist only, what we really want is modifying the top-level stacktrace-gps.js and building with make.

**Comment by niemyjski** [comment]
whoops.. missed that I was pressed for time... The call to send in _xhr was throwing the exception, I did a try catch because it caught it and I had access to return a promise.

**Comment by niemyjski** [comment]
Updated the pr

**Comment by niemyjski** [comment]
Can you please review my pull request.

**Comment by eriwen** [comment]
stacktrace-gps.min.js should've been modified as well. Did you run the make build before committing?

**Comment by niemyjski** [comment]
I didn't run make... I guess I need to spend the time and ensure I have xyz installed..

**Comment by niemyjski** [comment]
You're going to have to publish a guide on building... I'm under a time crunch and npm install didn't allow me to run make from windows and npm install make -g didn't help either...

**Comment by eriwen** [comment]
Yep, a developer guide is one of the more important things we hope to have before release.

You should be able to run make on windows using this: 
http://gnuwin32.sourceforge.net/packages/make.html

**Comment by eriwen** [comment]
Make that http://gnuwin32.sourceforge.net/packages/make.htm

Sorry, typo

**Comment by niemyjski** [comment]
I'm not sure I want to install that to be honest... Why are we using things that don't work cross plat very easy when there are build systems like grunt and gulp?

**Comment by niemyjski** [comment]
Yeah, I'm not installing make on my windows box that I use for other things. Please accept this pull request or copy the code changes I made and run it.

**Pull request closed without merging**
